import { User } from '../models/user';
 export const MOCK_USERS:User[]=[
     {
         id:12,
         firstName:"sgfsagsdagas",
         lastName:"asgasdfasdf",
         email:"fsfgsfgsadg@gmail.com",
         role:"Role_User",
         password:"akdnkjasdf",
         contactNumber:234324
     },
     {
        id:22,
        firstName:"sgfsagsdagas",
        lastName:"asgasdfasdf",
        email:"fsfgsfgsadg@gmail.com",
        role:"Role_User",
        password:"akdnkjasdf",
        contactNumber:234324
    },
    {
        id:42,
        firstName:"sgfsagsdagas",
        lastName:"asgasdfasdf",
        email:"fsfgsfgsadg@gmail.com",
        role:"Role_User",
        password:"akdnkjasdf",
        contactNumber:234324
    },
    {
        id:92,
        firstName:"sgfsagsdagas",
        lastName:"asgasdfasdf",
        email:"fsfgsfgsadg@gmail.com",
        role:"Role_User",
        password:"akdnkjasdf",
        contactNumber:234324
    },
    {
        id:222,
        firstName:"sgfsagsdagas",
        lastName:"asgasdfasdf",
        email:"fsfgsfgsadg@gmail.com",
        role:"Role_User",
        password:"akdnkjasdf",
        contactNumber:234324
    }];